auth:
  jwt:
    issuer: team.sparta.com
    secret: c5t6gzuXneIM3d0Eafy2F3MrkK41BUfD
    accessTokenExpirationHour: 168

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      highlight_sql: true
      use_sql_comments: true
      default_batch_fetch_size: 500
      hibernate:
        format_sql: true
    open-in-view: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url : jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres
    username : postgres.quydnpzzesfybdmsddyu
    password : MygnlKjWIgchzP9k

#    driver-class-name: org.postgresql.Driver
#    url: jdbc:h2:mem:test
#    username: sa
#    password:
#  sql:
#    init:
#      mode: embedded
#  h2:
#    console:
#      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
      springframework:
        security: debug