auth:
  jwt:
    issuer: team.sparta.com
    secret: c5t6gzuXneIM3d0Eafy2F3MrkK41BUfD
    accessTokenExpirationHour: 168

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      highlight_sql: true
      use_sql_comments: true
      default_batch_fetch_size: 500
      hibernate:
        format_sql: true
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: http://localhost:8080/oauth2/callback/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: kakao
            scope:
              - profile_nickname
              - account_email

          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/oauth2/callback/naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: naver
#            scope:
#              - profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response



  datasource:
        driver-class-name: org.postgresql.Driver
        url : jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres
        username : postgres.quydnpzzesfybdmsddyu
        password : MygnlKjWIgchzP9k
#
#    url: jdbc:h2:mem:test
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  sql:
#    init:
#      mode: embedded
#  h2:
#    console:
#      enabled: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
      springframework:
        security: debug
